version: "3.0"
services:
  
  election-tp-java:
    build:
      context: .
      dockerfile: examples/election_basic/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: election-tp-java-local:${ISOLATION_ID}
    volumes:
      - ./:/project/sawtooth-sdk-java
    container_name: election-tp-java
    command: election-tp-java tcp://validator:4004
    depends_on:
      - validator
    stop_signal: SIGKILL 

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: sawtooth-settings-tp-default
    depends_on:
    - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004

  validator:
    image: hyperledger/sawtooth-validator:1.0
    container_name: sawtooth-validator-default
    expose:
    - 4004
    ports:
    - "4004:4004"
    # start the validator with an empty genesis batch
    entrypoint: "bash -c \"\
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
        sawadm genesis config-genesis.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
        \""
    tty: true
    stdin_open: true

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: sawtooth-rest-api-default
    ports:
    - "8008:8008"
    depends_on:
    - validator
    entrypoint: sawtooth-rest-api -C tcp://validator:4004 --bind rest-api:8008

  shell:
    image: hyperledger/sawtooth-all:1.0
    container_name: sawtooth-shell-default
    depends_on:
    - rest-api
    - election-tp-java
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""
    tty: true
    stdin_open: true
